{{- if and .Values.rbac.create .Values.rbac.metricsAuth.enabled .Values.manager.metricsSecure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "modelsrv-k8s-sensor.fullname" . }}-metrics-auth
  labels:
    {{- include "modelsrv-k8s-sensor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "modelsrv-k8s-sensor.fullname" . }}-metrics-auth
  labels:
    {{- include "modelsrv-k8s-sensor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "modelsrv-k8s-sensor.fullname" . }}-metrics-auth
subjects:
  - kind: ServiceAccount
    name: {{ include "modelsrv-k8s-sensor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
