apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelsrv-k8s-sensor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelsrv-k8s-sensor.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "modelsrv-k8s-sensor.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
