# permissions for end users to view findingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: emeland-k8s
    app.kubernetes.io/managed-by: kustomize
  name: findingrule-viewer-role
rules:
- apiGroups:
  - structure.emeland.io
  resources:
  - findingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - structure.emeland.io
  resources:
  - findingrules/status
  verbs:
  - get
