# permissions for end users to view systeminstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: systeminstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: emeland-k8s
    app.kubernetes.io/part-of: emeland-k8s
    app.kubernetes.io/managed-by: kustomize
  name: systeminstance-viewer-role
rules:
- apiGroups:
  - structure.emeland.io
  resources:
  - systeminstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - structure.emeland.io
  resources:
  - systeminstances/status
  verbs:
  - get
