# permissions for end users to edit systems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: emeland-k8s
    app.kubernetes.io/managed-by: kustomize
  name: system-editor-role
rules:
- apiGroups:
  - structure.emeland.io
  resources:
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - structure.emeland.io
  resources:
  - systems/status
  verbs:
  - get
