## Append samples of your project ##
resources:
- structure_v1alpha1_system.yaml
- structure_v1alpha1_api.yaml
- structure_v1alpha1_component.yaml
- structure_v1_systeminstance.yaml
- structure_v1alpha1_systeminstance.yaml
- structure_v1alpha1_findingrule.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
