apiVersion: structure.emeland.io/v1alpha1
kind: API
metadata:
  labels:
    app.kubernetes.io/name: emeland-k8s
    app.kubernetes.io/managed-by: kustomize
  name: api-sample
spec:
  # TODO(user): Add fields here
