- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - structure.emeland.io
  resources:
    - apis
    - components
    - systeminstances
    - systems
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - structure.emeland.io
  resources:
    - apis/finalizers
    - components/finalizers
    - systeminstances/finalizers
    - systems/finalizers
  verbs:
    - update
- apiGroups:
    - structure.emeland.io
  resources:
    - apis/status
    - components/status
    - systeminstances/status
    - systems/status
  verbs:
    - get
    - patch
    - update
